

# This file was *autogenerated* from the file smaugt-bkz.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_512 = Integer(512); _sage_const_1024 = Integer(1024); _sage_const_140 = Integer(140); _sage_const_384 = Integer(384); _sage_const_247 = Integer(247); _sage_const_66 = Integer(66); _sage_const_7 = Integer(7); _sage_const_768 = Integer(768); _sage_const_2048 = Integer(2048); _sage_const_264 = Integer(264); _sage_const_20 = Integer(20); _sage_const_348 = Integer(348)
load("../framework/instance_gen.sage")

verbosity = _sage_const_2 

print("=============  SMAUGT-512")
# KS SMAUG-T1 and TiMER
n = _sage_const_512 
m = _sage_const_512 
q = _sage_const_1024 
h = _sage_const_140 

secret_table = [n-h, h//_sage_const_2 ]
error_table = [_sage_const_384 , _sage_const_247 , _sage_const_66 , _sage_const_7 ]
D_s = get_distribution_from_table(secret_table, n)
D_e = get_distribution_from_table(error_table, _sage_const_1024 )

"""
_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=20)
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)
"""

print("=============  SMAUGT-768")
# KS SMAUG-T3
n = _sage_const_768 
m = _sage_const_768 
q = _sage_const_2048 
h = _sage_const_264 

secret_table = [n-h, h//_sage_const_2 ]
D_s = get_distribution_from_table(secret_table, n)

_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=_sage_const_20 )
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)


print("=============  SMAUGT-1024")
# KS SMAUG-T5
n = _sage_const_1024 
m = _sage_const_1024 
q = _sage_const_2048 
h = _sage_const_348 

secret_table = [n-h, h//_sage_const_2 ]
D_s = get_distribution_from_table(secret_table, n)

_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=_sage_const_20 )
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)

