

# This file was *autogenerated* from the file smaugt-bkz.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1024 = Integer(1024); _sage_const_2048 = Integer(2048); _sage_const_348 = Integer(348); _sage_const_512 = Integer(512); _sage_const_10 = Integer(10); _sage_const_3 = Integer(3); _sage_const_16 = Integer(16); _sage_const_20 = Integer(20)
load("../framework/instance_gen.sage")

verbosity = _sage_const_2 

"""
#########################
# KS SMAUG-T1 and TiMER #
#########################
print("=============  SMAUGT-512-LWE")
n = 512
m = 512
q = 1024
h = 140

secret_table = [n-h, h//2]
error_table = [384, 247, 66, 7]
D_s = get_distribution_from_table(secret_table, n)
D_e = get_distribution_from_table(error_table, 1024)

_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=20)
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)

print("=============  SMAUGT-512-LWR")
p = 256

secret_table = [6, 1]
D_s = get_distribution_from_table(secret_table, 8)

_, _, inst = initialize_from_LWR_instance(DBDD_predict_diag, n, q, p,
                                          m, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=20)
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)


###############
# KS SMAUG-T3 #
###############
print("=============  SMAUGT-768-LWE")
n = 768
m = 768
q = 2048
h = 264

secret_table = [n-h, h//2]
D_s = get_distribution_from_table(secret_table, n)

_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=20)
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)

print("=============  SMAUGT-768-LWR")
p = 512

secret_table = [2, 1]
D_s = get_distribution_from_table(secret_table, 4)

_, _, inst = initialize_from_LWR_instance(DBDD_predict_diag, n, q, p,
                                          m, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=20)
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)


###############
# KS SMAUG-T5 #
###############
print("=============  SMAUGT-1024-LWE")
"""
n = _sage_const_1024 
m = _sage_const_1024 
q = _sage_const_2048 
h = _sage_const_348 

secret_table = [n-h, h//_sage_const_2 ]
D_s = get_distribution_from_table(secret_table, n)

"""
_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=20)
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)
"""

print("=============  SMAUGT-1024-LWR")
p = _sage_const_512 

secret_table = [_sage_const_10 , _sage_const_3 ]
D_s = get_distribution_from_table(secret_table, _sage_const_16 )

_, _, inst = initialize_from_LWR_instance(DBDD_predict_diag, n, q, p,
                                          m, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=_sage_const_20 )
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)

